app:
  environment: test
  debug: true
  log_level: debug

database:
  host: localhost
  user: postgres
  password: postgres
  db_name: ccards_local_test
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 1m
  conn_max_idle_time: 30s

server:
  port: 8081

jwt:
  secret: test-jwt-secret-key-for-testing-only
  access_token_duration: 5m
  refresh_token_duration: 24h

redis:
  host: localhost
  port: 6379
  password: ""
  db: 1  # Use different DB for tests